### ISSUE TITLE
question - VxWireguard-Generator has "sd-wan" as one of its "tags" did you envision an sd-wan controller for this

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#11]
Just curious but VxWireguard-Generator has "sd-wan" as one of its "tags" did you envision one of the open source 
sd-wan controllers for use with it eventually?

**Comment by m13253** [comment]
Thank you for your message!

I would consider the interoperability between VWGen and other SD-WAN controllers. But I currently do not have this demands and do not own such equipment. So the implementation would be postponed.

Also eventually I would like to design a new protocol instead of relying on Wireguard and VXLAN. So it might not be worthy implementing this feature right now.

If you are interested and are willing to help, I would appreciate very much if you can contribute this feature to the project.
